const fs=require('fs'); const assert=require('assert'); const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const obj=fs.readFileSync(path.join(ROOT,'engine/object-library-p2-1.js'),'utf8');
const rt=fs.readFileSync(path.join(ROOT,'engine/npc-runtime.js'),'utf8');
const map=fs.readFileSync(path.join(ROOT,'map-test/index.html'),'utf8');
const city=fs.readFileSync(path.join(ROOT,'data/civilization-cities.js'),'utf8');
const cuo=fs.readFileSync(path.join(ROOT,'cuo-lab/index.html'),'utf8');
for(const joint of ['TranslucentElbow','TranslucentKnee','RockyElbow','RockyKnee']) assert(obj.includes(joint),`joint missing ${joint}`);
assert(obj.includes('npcVisualScale = 0.62'),'translucent visual scale 0.62');
assert(obj.includes('npcVisualScale = 0.56'),'rocky visual scale 0.56');
assert((obj.match(/npcGroundOffset = 0\.9/g)||[]).length>=2,'ground offset +0.90 both species');
assert(rt.includes('Math.atan2(-dz, dx)'),'motion/player facing uses +X model front axis');
assert(rt.includes('syncKinematics(state)'),'kinematic joint synchronization active');
assert(rt.includes('dialogueEnvelope'),'dialogue gesture envelope active');
assert(rt.includes('FORWARD_FOREARM_ANGLE = Math.PI / 2'),'dialogue bends forearm forward to approximately 90 degrees');
assert(rt.includes('yawAmplitude = vigilant ? 0.34'),'vigilance head motion visibly amplified');
assert(obj.includes('handAnchor.add(hand)') && obj.includes('handAnchor.add(digit)'),'translucent hand and fingers share a moving hand anchor');
assert(obj.includes('plate.userData.jointRole = "elbow"'),'Rocky elbow decoration identified on both side-generated arms');
assert(rt.includes('syncRockyElbowDecor(state)'),'Rocky elbow decorations follow both elbow joints');
assert(city.includes('position: Object.freeze([22, 0, 30])'),'TinyCity merchant moved to expected central courtyard');
assert(rt.includes('state.lookBlend += (strength - state.lookBlend) * 0.18'),'player tracking response amplified');
for(const action of ['rest','calm','vigilance','dialogue','track','flee','return']) assert(map.includes(`data-npc-test="${action}"`),`MAP_Test control missing ${action}`);
assert(map.includes('Joueur test en orbite'),'MAP_Test tracking demo present');
assert(cuo.includes('../engine/object-library-p2-1.js?v=npc-r41-visual') && cuo.includes('../engine/npc-runtime.js?v=npc-r41-visual'),'CUO Lab must load current NPC visual/runtime assets');
console.log('PASS npc-r4-animation-contract');
